import type { Holding, PriceRow } from './types';

export const SEED_ROLES: string[] = [
  'Landlord',
  'Building Materials',
  'Power Grid',
  'Roads',
  'Foremen',
  'Operating System',
  'Security Guards',
  'Crypto Mining',
  'MarTech',
  'Search & AI',
  'Chip Litho',
  'Foundry',
  'Nuclear Power',
];

// 52-week highs as of 2026-03-01 (used to pre-populate before first API refresh)
const Z: PriceRow = {
  price: 0,
  ma200: 0,
  h52: 0,
  dailyChange: 0,
  dailyChangePct: 0,
  yearChangePct: 0,
};
export const SEED_PRICES: Record<string, PriceRow> = {
  AMZN:  { ...Z, h52: 258.60 },
  ANET:  { ...Z, h52: 164.94 },
  ASML:  { ...Z, h52: 1547.22 },
  BE:    { ...Z, h52: 180.90 },
  BITF:  { ...Z, h52: 6.60 },
  BMNR:  { ...Z, h52: 161.00 },
  CEG:   { ...Z, h52: 412.70 },
  DDOG:  { ...Z, h52: 201.69 },
  GOOGL: { ...Z, h52: 349.00 },
  NVDA:  { ...Z, h52: 212.19 },
  PLTR:  { ...Z, h52: 207.52 },
  TSM:   { ...Z, h52: 390.21 },
  VRT:   { ...Z, h52: 264.86 },
  ZETA:  { ...Z, h52: 24.90 },
  ZS:    { ...Z, h52: 336.99 },
};

export const SEED_HOLDINGS: Holding[] = [
  // ── Core ──────────────────────────────────────────────────────
  {
    id: 'AMZN',
    ticker: 'AMZN',
    name: 'Amazon',
    role: 'Landlord',
    category: 'core',
    positions: [
      { broker: 'Moomoo',    shares: 0.5332, avgCost: 206.077 },
      { broker: 'Robinhood', shares: 18.063, avgCost: 231.11 },
    ],
    ath: null,
    doubleDown: true,
  },
  {
    id: 'ANET',
    ticker: 'ANET',
    name: 'Arista Networks',
    role: 'Roads',
    category: 'core',
    positions: [
      { broker: 'Moomoo', shares: 6.6647, avgCost: 132.779 },
    ],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'BE',
    ticker: 'BE',
    name: 'Bloom Energy',
    role: 'Power Grid',
    category: 'core',
    positions: [
      { broker: 'Moomoo',    shares: 0.512, avgCost: 154.238 },
      { broker: 'Robinhood', shares: 25,    avgCost: 138.64 },
    ],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'DDOG',
    ticker: 'DDOG',
    name: 'Datadog',
    role: 'Foremen',
    category: 'core',
    positions: [
      { broker: 'Moomoo', shares: 1.8806, avgCost: 112.22 },
    ],
    ath: 201.69,
    doubleDown: false,
  },
  {
    id: 'NVDA',
    ticker: 'NVDA',
    name: 'NVIDIA',
    role: 'Building Materials',
    category: 'core',
    positions: [
      { broker: 'Moomoo',    shares: 0.4048, avgCost: 186.833 },
      { broker: 'Robinhood', shares: 25,     avgCost: 174.26 },
    ],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'PLTR',
    ticker: 'PLTR',
    name: 'Palantir',
    role: 'Operating System',
    category: 'core',
    positions: [
      { broker: 'Moomoo',    shares: 0.8335, avgCost: 131.518 },
      { broker: 'Robinhood', shares: 30,     avgCost: 134.57 },
    ],
    ath: null,
    doubleDown: true,
  },
  {
    id: 'VRT',
    ticker: 'VRT',
    name: 'Vertiv',
    role: 'Power Grid',
    category: 'core',
    positions: [
      { broker: 'Moomoo', shares: 3.4155, avgCost: 257.787 },
    ],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'ZS',
    ticker: 'ZS',
    name: 'Zscaler',
    role: 'Security Guards',
    category: 'core',
    positions: [
      { broker: 'Moomoo', shares: 1.7793, avgCost: 147.513 },
    ],
    ath: 376.11,
    doubleDown: false,
  },
  // ── Extra ─────────────────────────────────────────────────────
  {
    id: 'BITF',
    ticker: 'BITF',
    name: 'Bitfarms',
    role: 'Crypto Mining',
    category: 'extra',
    positions: [
      { broker: 'Robinhood', shares: 621.142, avgCost: 2.66 },
    ],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'BMNR',
    ticker: 'BMNR',
    name: 'BitMiner',
    role: 'Crypto Mining',
    category: 'extra',
    positions: [
      { broker: 'Moomoo',    shares: 7,       avgCost: 19.813 },
      { broker: 'Robinhood', shares: 100.111, avgCost: 19.31 },
    ],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'ZETA',
    ticker: 'ZETA',
    name: 'Zeta Global',
    role: 'MarTech',
    category: 'extra',
    positions: [
      { broker: 'Robinhood', shares: 175, avgCost: 16.99 },
    ],
    ath: null,
    doubleDown: false,
  },
  // ── Wishlist ──────────────────────────────────────────────────
  {
    id: 'ASML',
    ticker: 'ASML',
    name: 'ASML Holding',
    role: 'Chip Litho',
    category: 'wishlist',
    positions: [],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'CEG',
    ticker: 'CEG',
    name: 'Constellation Energy',
    role: 'Nuclear Power',
    category: 'wishlist',
    positions: [],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'GOOGL',
    ticker: 'GOOGL',
    name: 'Alphabet',
    role: 'Search & AI',
    category: 'wishlist',
    positions: [],
    ath: null,
    doubleDown: false,
  },
  {
    id: 'TSM',
    ticker: 'TSM',
    name: 'TSMC',
    role: 'Foundry',
    category: 'wishlist',
    positions: [],
    ath: null,
    doubleDown: false,
  },
];
